# Generated by Django 3.1.6 on 2021-04-07 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='menu',
        ),
    ]
